### ISSUE TITLE
Fork to support table tennis?

### ISSUE THREAD

**Issue by that0n3guy** [matco/badminton#22]
This is a great app.  One of the better one's I've used for my Garmin actually.

I play a lot of table tennis and it would be awesome if you could modify it for table tennis (or release a new app).

Only couple of differences are that able tennis goes to 11, you can serve from anywhere on singles, always serves from right quadrant in doubles, you serve 2 times then server changes no matter who scores.

What are you're thoughts?

**Comment by matco** [comment]
Hi!

Thanks for your kind message.

Unfortunately, I've lost my interest in the development of Garmin applications. I think that Garmin totally messed up with their ecosystem (customer products and developer SDK). Even the development of a very simple app such as the Badminton Score Tracker is difficult mainly because of the number of different watches. I've already expressed the problems on the Garmin forum (see here https://forums.garmin.com/developer/connect-iq/f/discussion/244877/wake-up-garmin) but the Garmin team does not care. You will find many posts like mine from people complaining about Garmin.

Moreover, I created this app because I play badminton and because I'm a curious developer who love trying new languages and platforms. I have never been interested in selling the app or gaining visibility. My app is more like an experiment, so I have already reached my goal and I'm happy that people like you enjoy the app.

However, I think it would be easy to adapt this app for table tennis. It's already possible to configure the maximum number of points and disable sounds (You mentioned that in your e-mail) via the Garmin Connect app. The main challenge is to adapt the UI. By the way, the code of the Badminton app is licensed under the most permissive license that exists, so it's no problem to fork or copy paste this repo.

If someone is willing to develop this new app, I'm here to help.
